### ISSUE TITLE
Invalid argument `activeCoordinates[0]` passed into NGLComponent with ID "viewport"

### ISSUE THREAD

**Issue by IvoLeist** [lilyminium/dash-ngl#1]
Hello lilyminium,

while searching for a better molecule viewer than molecule3dviewer (https://dash.plot.ly/dash-bio/molecule3dviewer) I stumbled over your repo.
But unfortunately the newest dash versions seems to have broken your component...

> Invalid argument `activeCoordinates[0]` passed into NGLComponent with ID "viewport".
> Expected `array`.
> Was supplied type `object`.

Below are the used dash versions
```
dash                      1.8.0                    pypi_0    pypi
dash-bio                  0.4.6                    pypi_0    pypi
dash-bio-utils            0.0.4                    pypi_0    pypi
dash-core-components      1.7.0                    pypi_0    pypi
dash-daq                  0.2.2                      py_0    conda-forge
dash-html-components      1.0.2                    pypi_0    pypi
dash-renderer             1.2.3                    pypi_0    pypi
dash-table                4.6.0                    pypi_0    pypi
```

and here python:

> Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
> [GCC 7.3.0] :: Anaconda, Inc. on linux

In case you do not any longer maintain that project:
I would try to come up with my own dash-ngl component.
I hope you don't mind if I take parts of your code since it looks like a promising template to get started.

Best,
Ivo

**Comment by lilyminium** [comment]
Thanks @IvoLeist! I'll take a look at this tomorrow, it's been a while :-)

**Comment by lilyminium** [comment]
@IvoLeist I updated some versions, and also put in a few more features that I had lying around on another version. Could you let me know if it works? Documentation coming soon, but I did also update `usage.py` which you can run to see a small demo.

**Comment by IvoLeist** [comment]
@lilyminium thanks a lot for the quick fix and the addition of these "few" more features. 
It works for me. However, some of the features seem to cause some issues:
If I e.g. use a .cif file and select Type: "cartoon" and then e.g. color scheme "volume"
The following error arises:

> this.atomColor is not a function

You do not need to fix that issue since we decided to develop our own dash ngl (mol*) 
component (https://github.com/IvoLeist/dash_ngl)
since yours does not really fits our need + your code base is quite complex.

An insight I wanted to share with you while I was developing mine
I would suggest to replace that code part with
```
// load text if it's changed
        if (prevProps.data !== data) {
            setTimeout(this.loadData(data), 500)
        }

```
with
```
shouldComponentUpdate(nextProps) {
  if (prevProps.data !== data) {
            setTimeout(this.loadData(data), 500)
        }
}

```
In my case it greatly improved the performance.
Have not tried it for yours but I would give it a shot.

Best,
Ivo

**Comment by lilyminium** [comment]
Thanks @IvoLeist, your version looks good!
